### ISSUE TITLE
Midsummer Festival

### ISSUE THREAD

**Issue by KiritoXvXKillMeNow** [wowironforges/IronForges#2]
### What client do you play on?

enUS

### Faction

Horde

### Content Phase:

Generic

### Current Behaviour

The quest "Incense for the Festival Scorchlings" cannot be turned in. I picked up the quest in Orgrimmar and went to Razor Hill, Durotar to turn the quest in. The scorchling was not there.

Will see if any others have spawned after I come back from work.

### Expected Blizzlike Behaviour

The scorchlings should spawn in settlements in order to complete the quest.

### Source

I don't know what to put in this section.

### Steps to reproduce the problem

Go to Orgrimmar and accept the quest "Incense for the Festival Scorchlings"
Go to Razor Hill, where the scorchling should be there.
The scorchling was not there.

### Extra Notes

Edit: There is a scorchling to turn in the quest in Trisfall Glades

### Operating system

Windows 11

### Customizations

None

### Realm in Iron-Old

Faerlina

**Comment by iron-old** [comment]
Hello, thank you very much for reporting.  If you can attach a YouTube video or even pictures that would be even better. :)

**Comment by wowironforges** [comment]
Bug fixed!
