### ISSUE TITLE
Weapons Enchantment

### ISSUE THREAD

**Issue by Ka-Anor** [wowironforges/IronForges#3]
### What client do you play on?

enGB

### Faction

Both

### Content Phase:

40-49

### Current Behaviour

Unable to enchant weapons acquired as a quest reward. Any enchantment outside of class-specific spells (shaman, warlock) cannot be applied to the weapon. I have tried different oils (wizard, mana), sharpening and weightstones, as well as +damage weapon enchantment from enchanting profession. The message given is "Target is too low level.", regardless of the actual weapon ilvl or character level.

### Expected Blizzlike Behaviour

I should be able to enchant any weapon matching the specified level of enchantment.

### Source

Gameplay

### Steps to reproduce the problem

Have weapon acquired from quest reward in inventory or equipped.
Have an enchantment in inventory (Wizard Oil, Sharpening Stone etc.).
Try using enchantment on the weapon.

### Extra Notes

Any and all weapon enchantments (as far as I had and tried them) work normally on weapons *not* acquired as a quest reward.

### Operating system

Windows 11

### Customizations

None

### Realm in Iron Forges

Main

**Comment by wowironforges** [comment]
I don't fear a bug like you described.  Perhaps you can provide us with what item or ID you are specifically trying to enchant.  I'll close this issue, I'll reopen anything.
