### ISSUE TITLE
Warlock Pets Bugged

### ISSUE THREAD

**Issue by Ka-Anor** [wowironforges/IronForges#4]
### What client do you play on?

enGB

### Faction

Alliance

### Content Phase:

50-59

### Current Behaviour

Since level 40 I have noticed my summoned demons do not work properly. I am currently level 42 affliction warlock. When I summon a Succubus or Felhunter it works properly, however, if I teleport somewhere, use hearthstone, use flightmaster or sometimes even just use my mount, it occasionally (not every time) disappears. When I dismount or appear, the Felhunter/Succubus is either just gone (no summoned demon), or it is suddenly a different one. Aka, I had a Succubus summoned, then I mount up, go somewhere, I dismount, and I have an Imp as a summoned pet. Or I had a Felhunter summoned, I use my hearthstone and I either have no summoned demon, or I have a Succubus.
I have NOT noticed this problem with Imp or Voidwalker, or on my (horde) demonology warlock's Felguard.

### Expected Blizzlike Behaviour

A summoned demon should always stay the same through any travelling and also stay summoned (unless killed or dismissed).

### Source

My gameplay.

### Steps to reproduce the problem

1. Summon Succubus/Felhunter.
2. Mount up and travel or use a flightmaster.
3. Check if you still have a demon pet, and if it is the same one.

### Operating system

Windows 11

### Customizations

None

### Realm in Iron Forges

Main

**Comment by wowironforges** [comment]
Thanks to you for letting us know about this issue, we will check it out!

**Comment by wowironforges** [comment]
We are currently unable to reproduce this issue, so we have decided to keep it closed for now.
