### ISSUE TITLE
Disconnecting Glitch

### ISSUE THREAD

**Issue by Pythol** [wowironforges/IronForges#8]
### What client do you play on?

enUS

### Faction

Alliance

### Content Phase:

Generic

### Current Behaviour

When i was on a ship and i move my charakter i got suddenly disconnected from the server. This happened twice. While getting of the ship after travelling from the azuremist isle and the second one from Auberdine to Darnassus.

### Expected Blizzlike Behaviour

Shouldnt happen

### Source

None

### Steps to reproduce the problem

1. Get on a ship and move while the ship is travelling i guess

### Operating system

Windows 11

### Customizations

None

### Realm in Iron Forges

Main

**Comment by wowironforges** [comment]
Something similar in https://github.com/wowironforges/IronForges/issues/5
